################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &ExportingEntityOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ExportingEntityOrgMSP

        # ID to load the MSP definition as
        ID: ExportingEntityOrgMSP

        MSPDir: ../crypto-config/peerOrganizations/exportingentityorg.trade.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.exportingentityorg.trade.com
              Port: 7051
